# sanitize:file
name: Change Request Report Draft
description: Full change request report template outlining the entire development process
title: "Change Request Report Draft: Release {solution} vX.y.z"
labels: ["release"]
body:
  - type: textarea
    attributes:
      label: Report Title
      value: |
        # {solution} vX.y.z Release Change Request Report Draft
  - type: markdown
    attributes:
      value: |
        ## Repositories
  - type: textarea
    attributes:
      label: Repositories
      description: Provide links to production and internal repositories and registries for the solution and assets, including samples and documentation.
      value: |
        1. [Internal development repository](https://github.com/Dynamsoft/document-scanner-javascript-dev/)
        2. [Internal `npm` repository](https://npm.scannerproxy.com:802/-/web/detail/dynamsoft-document-scanner)
        3. [Production repository](https://github.com/Dynamsoft/document-scanner-javascript)
        4. [Production `npm` repository](https://www.npmjs.com/package/dynamsoft-document-scanner)
        5. [Documentation repository](https://github.com/dynamsoft-docs/mobile-document-scanner-docs-js)
  - type: markdown
    attributes:
      value: |
        ## Proposed Timeline
  - type: textarea
    attributes:
      label: Proposed Timeline
      description: Outline the estimated schedule, including milestones, target dates, and review checkpoints.
      value: |
        2026-01-05: Begin development and upgrade process
        2026-01-06 - 2026-01-09: Internal testing
        2026-01-12: Public release
  - type: markdown
    attributes:
      value: |
        ## Resource Requirements
  - type: textarea
    attributes:
      label: Resource Requirements
      description: List all resources required, such as staff time, additional tools, or system access.
      value: |
        Alice - main developer/product manager
        Bob - consulting for release workflow
        Charlie - testing and QA
        Dylan - supervisor
  - type: markdown
    attributes:
      value: |
        ## Description
  - type: textarea
    attributes:
      label: Description
      description: Provide a clear summary of the requested change - what it is, why it is needed, and what outcome is expected.
      value: |
        Create the next scheduled feature release for MDS JS v1.4.0.

        This release consists of four main groups of changes:

        1. Update DCV JS to v3.2.4000.
        2. Use the new frame clarity value from DCV to select the best frame for capture.
        3. Add multi-page scanning support (with and without DDV) along with samples.
        4. Collected issues organised into the MDS JS v1.4.0 planner.
  - type: markdown
    attributes:
      value: |
        ## Impact Analysis
  - type: textarea
    attributes:
      label: Impact Analysis
      description: Describe the potential impact of the change on the project or operations, including any risks, dependencies, or possible side effects.
      value: |
        The breaking change introduced by switching the template file from `.html` to `.xml` may cause issues for a limited number of customers.

        Customers will need to update DCV resources if they are self-hosting them.
  - type: markdown
    attributes:
      value: |
        ## Proposed Solution

        ### Breaking Changes
  - type: textarea
    attributes:
      label: Breaking Changes
      description: Summarise breaking changes.
      value: |
        - Rename `document-scanner.ui.html` to `document-scanner.ui.xml`, the declarative UI configuration template for DCV.
          - This affects self-hosting users only: they must update the path in the `scannerViewConfig.cameraEnhancerUIPath` property accordingly and rebuild the library.
  - type: markdown
    attributes:
      value: |
        ### Highlighted Features
  - type: textarea
    attributes:
      label: Highlighted Features
      description: Summarise main features and improvements.
      value: |
        #### Scanning Capabilities
        
        - Select the clearest of multiple video frames on scan with `enableFrameVerification` (default `true`).
        - Add continuous scanning mode to make multiple scans on a single `launch()`, enabled by `enableContinuousScanning` (default `false`).
          - Add `onDocumentScanned` handler to get single scan results in continuous scanning mode.

        #### UI/UX Improvements

        - Remove the animated shutter spinner.
  - type: markdown
    attributes:
      value: |
        ### Samples
  - type: textarea
    attributes:
      label: Samples
      description: Summarise changes and improvements to samples.
      value: |
        - Add sample demonstrating minimal code to integrate MDS with Dynamsoft Document Viewer (DDV) to scan to PDF with continuous scanning.
        - Add minimal MDS-only continuous scanning sample.
  - type: markdown
    attributes:
      value: |
        ### Fixes
  - type: textarea
    attributes:
      label: Fixes
      description: Summarise fixes.
      value: |
        - Fix "Torch not supported" message appearing unnecessarily.
        - Update framework sample dependencies to resolve security vulnerabilities.
        - Remove memory leak caused by logging results to console.
  - type: markdown
    attributes:
      value: |
        ### Documentation
  - type: textarea
    attributes:
      label: Documentation
      description: Summarise changes and improvements to documentation.
      value: |
        - Add guides on using continuous scan mode and integrating with DDV.
        - Add full [`tsdoc`](https://tsdoc.org/) annotation coverage for all MDS APIs to bring API references to IDEs and allow content extraction with compatible development tools.
  - type: markdown
    attributes:
      value: |
        ### Dependencies
  - type: textarea
    attributes:
      label: Dependencies
      description: List direct core library dependencies (i.e. DCV).
      value: |
        - [Dynamsoft Capture Vision JS 3.2.4000](https://www.dynamsoft.com/capture-vision/docs/web/programming/javascript/release-notes/dcvb-3.html#324000-11112025)
  - type: markdown
    attributes:
      value: |
        ## Audit

        ### `npm audit`
  - type: textarea
    attributes:
      label: Audit
      description: Provide the output of `npm audit` (as well as a screenshot) when run on the development repository, with a timestamp.
      value: |
        Audit time: 2025 December 18
        
        ```shell
        [document-scanner-javascript-dev]$ date
        Thu 18 Dec 10:32:13 PST 2025
        [document-scanner-javascript-dev]$ npm audit
        found 0 vulnerabilities
        ```

        Result: `npm audit` found no vulnerabilities
  - type: markdown
    attributes:
      value: |
        ### `codeql database analyze`
  - type: textarea
    attributes:
      label: "`codeql database analyze`"
      description: Submit the SARIF output and HTML report summary from the local CodeQL scan run on the development repository.
      value: |
        Audit time: 2026 January 9

        Total findings: 0

        The CodeQL review yielded 0 findings based on the generated SARIF report.
  - type: markdown
    attributes:
      value: |
        ### Code Review
  - type: textarea
    attributes:
      label: Link the final code review/approval for a release.
      value: |
        Final release pull request in the production repository reviewed and approved by Tim: https://github.com/Dynamsoft/document-scanner-javascript-dev/pull/85
